apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: nginx-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  externalIPs:
  - 10.164.15.220
  selector:
    app: nginx-ingress
